from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from dapia_detection_api.models.base_model import Model
from dapia_detection_api.models.data1 import Data1
from dapia_detection_api import util

from dapia_detection_api.models.data1 import Data1  # noqa: E501

class Response200ClassifyAircraft1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """Response200ClassifyAircraft1 - a model defined in OpenAPI

        :param data: The data of this Response200ClassifyAircraft1.  # noqa: E501
        :type data: Data1
        """
        self.openapi_types = {
            'data': Data1
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Response200ClassifyAircraft1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Response_200_Classify_Aircraft_1 of this Response200ClassifyAircraft1.  # noqa: E501
        :rtype: Response200ClassifyAircraft1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Data1:
        """Gets the data of this Response200ClassifyAircraft1.


        :return: The data of this Response200ClassifyAircraft1.
        :rtype: Data1
        """
        return self._data

    @data.setter
    def data(self, data: Data1):
        """Sets the data of this Response200ClassifyAircraft1.


        :param data: The data of this Response200ClassifyAircraft1.
        :type data: Data1
        """

        self._data = data
