from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from dapia_detection_api.models.base_model import Model
from dapia_detection_api.models.data import Data
from dapia_detection_api import util

from dapia_detection_api.models.data import Data  # noqa: E501

class Response500ClassifyAircraft(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None, code=None):  # noqa: E501
        """Response500ClassifyAircraft - a model defined in OpenAPI

        :param result: The result of this Response500ClassifyAircraft.  # noqa: E501
        :type result: Data
        :param code: The code of this Response500ClassifyAircraft.  # noqa: E501
        :type code: int
        """
        self.openapi_types = {
            'result': Data,
            'code': int
        }

        self.attribute_map = {
            'result': 'result',
            'code': 'code'
        }

        self._result = result
        self._code = code

    @classmethod
    def from_dict(cls, dikt) -> 'Response500ClassifyAircraft':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Response_500_Classify_Aircraft of this Response500ClassifyAircraft.  # noqa: E501
        :rtype: Response500ClassifyAircraft
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> Data:
        """Gets the result of this Response500ClassifyAircraft.


        :return: The result of this Response500ClassifyAircraft.
        :rtype: Data
        """
        return self._result

    @result.setter
    def result(self, result: Data):
        """Sets the result of this Response500ClassifyAircraft.


        :param result: The result of this Response500ClassifyAircraft.
        :type result: Data
        """

        self._result = result

    @property
    def code(self) -> int:
        """Gets the code of this Response500ClassifyAircraft.


        :return: The code of this Response500ClassifyAircraft.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this Response500ClassifyAircraft.


        :param code: The code of this Response500ClassifyAircraft.
        :type code: int
        """

        self._code = code
