name: Python Unit Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Configuration de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Installation de Poetry
      run: |
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENV_IN_PROJECT: true

    - name: Exécution des tests
      run: poetry run python -m unittest discover -s ./dapia_detection_api/test/

