name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Configuration de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Installation de numpy
      run: pip install numpy

    - name: Installation de AdsbAnomalyDetector
      run: pip install AdsbAnomalyDetector

    - name: Installation de logging
      run: pip install logging

    - name: Installation de connexion
      run: pip install connexion

    - name: Installation de flask_testing
      run: pip install flask_testing

    - name: Installation de Poetry
      run: |
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENV_IN_PROJECT: true

    - name: Exécution des tests
      run: python -m unittest discover -s ./dapia_detection_api/test/

