name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Configuration de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Exécution des tests
      run: python -m unittest discover -s ./dapia_detection_api/test/

